### PR TITLE
Resource payload: send null value instead of empty string

### PR DESCRIPTION
**Pull request by shams-ahmed**
## Proposed changes:
- Send null values instead of an empty string

### Pre-requisites:
- [x] Reviewed code before asking reviewer <em>(Look at *Files Changed* below instead of Xcode)</em>.
- [x] Reviewed code format follows the style guide where possible.
- [x] Added tests where possible <em>(*compulsory for business logic and new classes)</em>.

### CODE REVIEW

**Comment by shams-ahmed** [comment]
Note PR is blocked by backend `Collector` service pre-validation checks on resource

**Comment by TheozZ79** [comment]
Oke

**Review by TheozZ79 — COMMENTED** [review]
Fine

**Review by TheozZ79 — APPROVED** [review]
Beter

**Pull request closed without merging**
